### PR TITLE
Add vue-language-server

### LINKED ISSUE #116: Support for vue-language-server ?
Will nvim-lsp support https://www.npmjs.com/package/vue-language-server ?

### PR DESCRIPTION
**Pull request by h-michael**
fix #116

### CODE REVIEW

**Comment by h-michael** [comment]
@dagadbm Would you try this or show me example project to test?

**Comment by dagadbm** [comment]
Thanks for this sorry for the late reply 

https://github.com/gothinkster/vue-realworld-example-app

Here is an example vueapp

**Comment by h-michael** [comment]
wait for https://github.com/neovim/neovim/pull/11838

**Comment by h-michael** [comment]
@justinmk Ready for merge :)

**Pull request merged**
