### PR TITLE
Make installer for sumneko_lua more robust

### PR DESCRIPTION
**Pull request by dlukes**
- I had to install clang for the installation to complete -> check for
  that up front
- quote PATH update (especially on WSL, PWD and PATH will easily contain
  whitespace)

### CODE REVIEW

**Comment by tjdevries** [comment]
Does sumneko always need clang to compile or can it use something else?

**Comment by dlukes** [comment]
I tried this on WSL2/Ubuntu with gcc installed, but it errored out instructing me to install clang. Grepping through the sumneko/lua-language-server checkout, I see lines like these:

```
lm.gcc = 'clang'
lm.gxx = 'clang++'
```

(Not familiar enough with the codebase and lua in general to draw any strong conclusions, but on the face of it, it indeed looks like clang specifically is needed.)

**Comment by tjdevries** [comment]
Awesome, thanks!

**Comment by tjdevries** [comment]
(I'll merge in a bit, just have to confirm one thing first)

**Pull request merged**
