### PR TITLE
Add bash language server

### PR DESCRIPTION
**Pull request by DanielVoogsgerd**
Short implementation for the bash language server.
Feedback is welcome.

### CODE REVIEW

**Comment by norcalli** [comment]
Since I'm about to improve installation support, I'll add that myself. Otherwise, the PR looks good, except that instead of modifying `README.md`, you should modify `README_preamble.md`, but that seems to confuse just about everyone, so that's not really your fault :sweat_smile: 

Thanks!

**Comment by DanielVoogsgerd** [comment]
That would make sense. I just copied what the others were doing.

Maybe it's a good idea to make a short "guide" as to how to contribute.

**Comment by norcalli** [comment]
Did you see CONTRIBUTING.md?

**Comment by DanielVoogsgerd** [comment]
Apologies, completely missed it.

Nice job in general btw!

**Pull request merged**
