### PR TITLE
use pcall for requiring a lsp module

### PR DESCRIPTION
**Pull request by h-michael**
fix: #191

### CODE REVIEW

**Comment by teto** [comment]
the error is then silent which makes debugging harder. maybe checkhealth catches it though

**Comment by tjdevries** [comment]
We should check the result of pcall, and if it is not OK, then warn the user that it failed. It is good not to crash though :)

**Comment by h-michael** [comment]
I think we should not this `pcall` result.
Because I added this `require` by this PR #109.
This `require` is only for loading existing modules.

**Comment by justinmk** [comment]
yeah this doesn't seem right, and would have made the problem in https://github.com/neovim/nvim-lsp/issues/191 much harder to find. It would silently do nothing instead of showing an error.

**Pull request closed without merging**
