### PR TITLE
Automatically fetch latest version of pyls_ms

### PR DESCRIPTION
**Pull request by mjlbach**
Not sure if this is the best approach, but this eliminates the need to manually bump the version.

### CODE REVIEW

**Comment by h-michael** [comment]
@mjlbach Awesome! I'll check it later.

@yaegassy Would you try this?

**Comment by mjlbach** [comment]
@h-michael we should consider adding an LspUpdate mechanism. Currently we have no way to overwrite previously installed language servers other than deleting from cache.

**Comment by yaegassy** [comment]
It works fine!
My [pull request](https://github.com/neovim/nvim-lsp/pull/181) is closed.

**Comment by mjlbach** [comment]
I should have done this from the beginning but couldn't figure out a good way to parse the xml when I originally made the config.

**Comment by h-michael** [comment]
>  we should consider adding an LspUpdate mechanism. Currently we have no way to overwrite previously installed language servers other than deleting from cache.

Yes, I'll impement it :)

**Pull request merged**
